### ISSUE TITLE
Not possible to translate records

### ISSUE THREAD

**Issue by p2media** [domjos1994/TimeLine#3]
When translating the content element and its related `tx_timeline_domain_model_timelineevent` records I get the following SQL Error:
```
SQL error 'Unknown column 't3_origuid' in 'field list'' (tx_timeline_domain_model_timelineevent:NEW5c6bd71f5e6fd686357019)
```

![screenhot-timeline](https://user-images.githubusercontent.com/10741828/53014627-4ff19480-3449-11e9-9ded-9616aa35823b.jpg)

**Comment by domjos1994** [comment]
Will be solved in version 0.0.4
